[package]
name = "opendut-util"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["settings"]
serde = ["dep:serde"]
settings = ["dep:config", "dep:home"]

[dependencies]
anyhow = { workspace = true }
config = { workspace = true, optional = true }
home = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
opentelemetry = { workspace = true, features = ["logs", "trace"] }
opentelemetry-otlp = { workspace = true, features = ["logs", "trace", "metrics"] }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio", "logs", "logs_level_enabled"] }
opentelemetry-appender-tracing = { workspace = true }
opentelemetry-semantic-conventions = { workspace = true }
simple_moving_average = { workspace = true }
sysinfo = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt", "tracing-log"] }
url = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[build-dependencies]
shadow-rs = { workspace = true }

[lints]
workspace = true
