# Required, otherwise ggshield considers the file to use the deprecated v1 format
version: 2

secret:
  # Exclude files and paths by globbing
  ignored-paths:
    # Exclude private keys dedicated for the test environment (development)
    - 'resources/development/tls/*.key'
    - '.ci/docker/keycloak/provision.sh'
    - '.ci/docker/netbird/management.json'
    - '.ci/docker/netbird/netbird-api-functions.sh'
    - '.ci/docker/netbird/turnserver.conf'
