[package]
name = "opendut-carl-api"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["codegen"]
codegen = ["tonic/prost", "tonic/codegen", "tonic-build/prost"]
client = [
    "codegen",
    "tokio",
    "tonic/default",
    "tonic/tls",
    "tonic-build/default",
]
wasm-client = [
    "codegen",
    "dep:tonic-web-wasm-client",
    "dep:leptos_oidc",
    "dep:chrono",
    "dep:tracing",
]

[dependencies]
opendut-types = { workspace = true }

cfg-if = { workspace = true }
log = { workspace = true }
prost = { workspace = true }
serde = { workspace = true, features = ["std", "derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true }
tonic = { workspace = true }
tonic-web-wasm-client = { workspace = true, optional = true }
url = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
leptos_oidc =  { workspace = true, optional = true }
chrono = { workspace = true, optional = true, default-features = false, features = ["clock", "serde", "wasmbind"] }
tracing = { workspace = true, optional = true }

[build-dependencies]
protobuf-src = { workspace = true }
tonic-build = { workspace = true }

[dev-dependencies]
googletest = { workspace = true }

[lints]
workspace = true
