name: Install Kernel Modules
description: Install Kernel Modules

runs:
  using: "composite"
  steps:
    - name: Install and load 'vcan' and 'can-gw' kernel modules
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
           linux-modules-extra-$(uname -r)
        sudo modprobe vcan
        sudo modprobe can-gw max_hops=2
