receivers:
 otlp:
   protocols:
     http:
       endpoint: 0.0.0.0:4318
     grpc:
       endpoint: 0.0.0.0:4317
 filelog:
   include: [ /etc/simple.log ]
   operators:
     - type: regex_parser
       regex: '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?P<sev>[A-Z]*) (?P<msg>.*)$'
       timestamp:
         parse_from: attributes.time
         layout: '%Y-%m-%d %H:%M:%S'
       severity:
         parse_from: attributes.sev


processors:
  batch:

  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: test

  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: test

exporters:
 debug:
   verbosity: detailed
 prometheus:
    endpoint: 0.0.0.0:8889
    const_labels:
      project: opendut
 otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
 loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tls:
      insecure: true
    headers:
      "X-Scope-OrgID": "tenant1"
    default_labels_enabled:
      exporter: true
      job: true

extensions:
 health_check:
 pprof:
   endpoint: :1888
 zpages:
   endpoint: :55679

service:
 extensions: [pprof, zpages, health_check]
 telemetry:
    logs:
        level: "debug"
 pipelines:
   traces:
     receivers: [otlp]
     processors: [batch]
     exporters: [debug, otlp/tempo]
   metrics:
     receivers: [otlp]
     processors: [batch]
     exporters: [debug, prometheus]
   logs:
     receivers: [otlp, filelog]
     processors: [batch, resource, attributes]
     exporters: [debug, loki]
