name: build-cleo
on:
  workflow_call:  # allow this workflow to be called from other workflows
    inputs:
      runs-on:
        default: "['ubuntu-latest']"
        required: false
        type: string

jobs:
  build-cleo:
    strategy:
      matrix:
        package:
          - name: opendut-cleo
            target: x86_64-unknown-linux-gnu
          - name: opendut-cleo
            target: armv7-unknown-linux-gnueabihf
          - name: opendut-cleo
            target: aarch64-unknown-linux-gnu
    name: "Build ${{ matrix.package.name }}-${{ matrix.package.target }}"
    runs-on: ${{ fromJson(inputs.runs-on) }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b #4.1.5
      - name: Install ARM GCC
        uses: ./.github/actions/install-arm-gcc
      - name: Rust setup
        uses: ./.github/actions/rust-setup
        with:
          cargo-cross: true

      - name: Build
        run: cargo ci opendut-cleo distribution-build --target=${{ matrix.package.target }}
      - name: "Upload CLEO build artifact ${{ matrix.package.name }}-${{ matrix.package.target }}"
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8
        with:
          name: "${{ matrix.package.name }}-${{ matrix.package.target }}-${{ github.sha }}"
          path: "./target/ci/cross/${{ matrix.package.target }}/release/${{ matrix.package.name }}"
          if-no-files-found: error
          retention-days: 1
