name: bundle-cleo
on:
  workflow_call:  # allow this workflow to be called from other workflows
    inputs:
      runs-on:
        default: "['ubuntu-latest']"
        required: false
        type: string

jobs:
  bundle-cleo:
    strategy:
      matrix:
        package:
          - name: opendut-cleo
            target: x86_64-unknown-linux-gnu
          - name: opendut-cleo
            target: armv7-unknown-linux-gnueabihf
          - name: opendut-cleo
            target: aarch64-unknown-linux-gnu
    name: "Bundle ${{ matrix.package.name }}-${{ matrix.package.target }}"
    runs-on: ${{ fromJson(inputs.runs-on) }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b #4.1.5
      - name: Rust setup
        uses: ./.github/actions/rust-setup

      - name: Download opendut-cleo
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935
        with:
          name: "${{ matrix.package.name }}-${{ matrix.package.target }}-${{ github.sha }}"
          path: "./target/ci/distribution/${{ matrix.package.target }}/${{ matrix.package.name }}/"
      - name: Download licenses
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935
        with:
          name: "licenses-${{ github.sha }}"
          path: "./target/ci/licenses"
      - name: Prepare Licenses
        run: cargo ci opendut-cleo distribution-copy-license-json --skip-generate --target=${{ matrix.package.target }}
      - name: Prepare Executables
        run: chmod +x ./target/ci/distribution/${{ matrix.package.target }}/${{ matrix.package.name }}/${{ matrix.package.name }}
      - name: Bundle
        run: cargo ci opendut-cleo distribution-bundle-files --target=${{ matrix.package.target }}
      - name: Validate distribution contents
        run: cargo ci opendut-cleo distribution-validate-contents --target=${{ matrix.package.target }}
      - name: "Upload CLEO bundle artifact ${{ matrix.package.name }}-${{ matrix.package.target }}.tar.gz"
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8
        with:
          name: "${{ matrix.package.name }}-${{ matrix.package.target }}-${{ github.sha }}.tar.gz"
          path: "./target/ci/distribution/${{ matrix.package.target }}/"
          if-no-files-found: error
          retention-days: 1
